//
//  CallViewModel.swift
//  FamilyTalk
//
//  Created by Dmitrii Gramoteev on 23.04.2026.
//

import Foundation
import Observation

enum CallState: Equatable {
    case idle
    case initiating
    case ringing
    case connected
    case ended
    case failed(String)
}

@Observable
@MainActor
final class CallViewModel {
    var callState: CallState = .idle
    var targetUser: User?
    var callType: CallType = .voice
    var callDuration: TimeInterval = 0
    var errorMessage: String?

    private var callTimer: Timer?
    private var currentCallId: String?
    private var currentTargetUserId: String?

    // MARK: - Outgoing Call

    /// Call this to start a call. Sends call:offer via socket.
    /// SDP must be generated by WebRTC (RTCPeerConnection.offer) before calling.
    func startCall(to user: User, type: CallType, sdp: String = "") {
        targetUser = user
        callType = type
        callState = .initiating
        errorMessage = nil
        currentTargetUserId = user.id

        SocketService.shared.sendOffer(targetUserId: user.id, sdp: sdp, type: type)
        callState = .ringing
    }

    // MARK: - Incoming Call

    /// Call this when SocketService.incomingCall fires (via .onChange in the view).
    func handleIncomingCall(_ event: IncomingCallEvent) {
        currentCallId = event.callId
        currentTargetUserId = event.initiatorId
        callType = event.type
        callState = .ringing
        // TODO: Set remote SDP on RTCPeerConnection: event.sdp
    }

    /// Answer the incoming call. SDP must be generated by WebRTC.
    func answerCall(sdp: String = "") {
        guard let callId = currentCallId, let targetUserId = currentTargetUserId else { return }
        SocketService.shared.sendAnswer(callId: callId, targetUserId: targetUserId, sdp: sdp)
        callState = .connected
        startCallTimer()
    }

    /// Decline the incoming call.
    func declineCall() {
        guard let callId = currentCallId, let targetUserId = currentTargetUserId else {
            reset()
            return
        }
        SocketService.shared.sendDecline(callId: callId, targetUserId: targetUserId)
        reset()
    }

    // MARK: - Remote Events

    /// Call this when SocketService.answeredCall fires (outgoing call was accepted).
    func handleCallAnswered(_ event: CallAnsweredEvent) {
        currentCallId = event.callId
        callState = .connected
        startCallTimer()
    }

    /// Call this when SocketService.remoteHangup or SocketService.remoteDeclined fires.
    func handleRemoteEnded() {
        stopCallTimer()
        callState = .ended
    }

    // MARK: - End Call

    func endCall() {
        guard let callId = currentCallId, let targetUserId = currentTargetUserId else {
            reset()
            return
        }
        SocketService.shared.sendHangup(callId: callId, targetUserId: targetUserId)
        stopCallTimer()
        callState = .ended
    }

    // MARK: - Duration

    var callDurationText: String {
        String(format: "%d:%02d", Int(callDuration) / 60, Int(callDuration) % 60)
    }

    // MARK: - Reset

    func reset() {
        stopCallTimer()
        callState = .idle
        targetUser = nil
        callDuration = 0
        currentCallId = nil
        currentTargetUserId = nil
        errorMessage = nil
    }

    // MARK: - Private

    private func startCallTimer() {
        callDuration = 0
        callTimer = Timer.scheduledTimer(withTimeInterval: 1, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in self?.callDuration += 1 }
        }
    }

    private func stopCallTimer() {
        callTimer?.invalidate()
        callTimer = nil
    }
}
